name: nvtphong200401_19127646_voicegpt
description: ChatGPT Plugin
homepage: https://github.com/nvtphong200401/voicegpt
version: 1.0.7+13

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.2.0
  flutter_hooks: ^0.18.5+1
  dio: ^5.0.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dartz: ^0.10.1
  markdown_widget: ^2.1.0
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/
