# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy a new version to the App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "C83X4T39ZZ",
      issuer_id: "92686f1a-3dd4-4446-ac27-0bbaa7f85e88",
      key_filepath: "./fastlane/AuthKey_C83X4T39ZZ.p8"
      )
    get_certificates(api_key: api_key, force: false, api_key: api_key)
    get_provisioning_profile(force: false, api_key: api_key)
    build_app(scheme: "Runner")
    upload_to_testflight(api_key: api_key,  team_id: "DNZCH8PD7Q", team_name: "DISTRIBUTED SYSTEM AND APPLICATION DEVELOPMENT JOINT STOCK COMPANY", skip_submission: true, ipa: "./Runner.ipa")
  end
end