# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Increment version code"
  lane :increment_vc do
  increment_version_code(
    gradle_file_path: "./app/build.gradle",
    version_code: 7
  )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # gradle(task: "clean bundleRelease")
    upload_to_play_store(
      json_key: json_key_file,
      track: "internal",
      release_status: "draft",
      skip_upload_changelogs: true,
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
