name: Build Release App Bundle
on:
  push:
    branches:
      - 'develop'
env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  build_and_deploy_android:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      # - uses: subosito/flutter-action@v1
      #   with:
      #     channel: ${{env.FLUTTER_CHANNEL}}
      #     flutter-version: ${{env.FLUTTER_VERSION}}

      # Creating the key.properties file
      - run: |
          echo keyPassword=\${{ secrets.KEY_STORE }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
      # Decoding base64 key into a file
      - run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/key.jks

      # Get dependencies and make assigned appbundle
      - run: | 
          flutter pub get
          flutter build appbundle
      # Make appbundle downloadable
      # - name: Upload artefato
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: appbundle
      #     path: build/app/outputs/bundle/release