name: Build Release App Bundle
on:
  pull_request:
    branches: ["master"]

jobs:
  deploy_ios:
    name: deploy iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: "develop"
    - run: |
          ls ${{ github.workspace }}
    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        cache: true
    - run: |
          flutter --version
          flutter pub get
    - name: run fastlane
      working-directory: ./ios
      run: |
          pod install
          fastlane release

  build_and_deploy_android:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: "develop"
    - run: |
          ls ${{ github.workspace }}
    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        cache: true
    - run: flutter pub get
    - name: Run fastlane
      working-directory: ./android
      run: fastlane deploy
# on: workflow_dispatch

# jobs:
#   build_and_deploy_android:
#     name: Build and Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: Decode Keystore
#       id: decode_keystore
#       uses: timheuer/base64-to-file@v1
#       with:
#         fileName: 'keystore/your_signing_keystore.jks'
#         encodedString: ${{ secrets.KEYSTORE }}
#     - uses: actions/checkout@v3
#     - name: set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
#     - name: Make gradlew executable
#       run: chmod +x ./gradlew
#     - name: build prod
#       run: ./gradlew app:bundleRelease
#       env:
#         SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
#         SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
#         SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
#     - name: Upload
#       uses: actions/upload-artifact@v2
#       with:
#         name: Build Artifacts
#         path: app/build/outputs/