# name: ios
# on:
#   push:
#     tags:
#       - v*

# jobs:
#   deploy_ios:
#     name: deploy iOS
#     runs-on: macos-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         ref: ${{ github.ref }}
#     - run: |
#           ls ${{ github.workspace }}
#     - uses: subosito/flutter-action@v2
#       with:
#         channel: "stable"
#         cache: true
#     - run: |
#           flutter --version
#           flutter pub get
#     - name: run fastlane
#       working-directory: ./ios
#       run: |
#           pod install
#           fastlane release
